# Generated by Django 5.2 on 2025-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_nba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='player_name',
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
