# Generated by Django 5.2 on 2025-06-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_nba', '0002_remove_teamplayer_player_name_team_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamplayer',
            unique_together={('team', 'player_id')},
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='status',
            field=models.CharField(choices=[('ON_TEAM', 'On Team'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='fantasy_nba.team'),
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='is_available',
        ),
    ]
