# Generated by Django 5.0.4 on 2025-10-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_nba', '0003_alter_teamplayer_unique_together_teamplayer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=20)),
                ('pick_number', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='fantasy_nba.team')),
            ],
            options={
                'ordering': ['pick_number'],
                'unique_together': {('team', 'pick_number'), ('team', 'player_id')},
            },
        ),
    ]
